export const actionTypes: {
  UPDATE_FORM_VALUE: Symbol;
  ADD_PRODUCT_VARIATION: Symbol;
  ADD_PRODUCT_IMAGE: Symbol;
} = {
  UPDATE_FORM_VALUE: Symbol('UPDATE_FORM_VALUE'),
  ADD_PRODUCT_VARIATION: Symbol('ADD_PRODUCT_VARIATION'),
  ADD_PRODUCT_IMAGE: Symbol('ADD_PRODUCT_IMAGE'),
};
